[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql"]

[phases.install]
cmds = ["cd backend && python -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python main.py"
