[build]
builder = "nixpacks"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { PYTHON_VERSION = "3.11" }

[environments.staging]
variables = { PYTHON_VERSION = "3.11" }
